Feature/ctv2
aws-ia/cloudformation-dynatrace-resource-providers pull request #6
Opened 2022-11-14 16:54 UTC by lukiwlosek

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-05 19:41 UTC, joshuadeanhall requested changes

2022-12-05 19:41 UTC, joshuadeanhall commented on Dynatrace-Environment-Metric/src/handlers.ts
> +	        { excludeExtraneousValues: true });;
Is there an extra `;` here?

2022-12-05 19:41 UTC, joshuadeanhall commented on Dynatrace-Environment-ServiceLevelObjective/src/handlers.ts
> +        delete (<any>result)?.errorBudgetMetricKey;
Why not just use `{ excludeExtraneousValues: true }` again to clean these up?

2022-12-06 10:13 UTC, lukiwlosek commented
Rerun the SLO resource as it was failing, had to delete some parameters as they do not appear in dynatrace api docs anyways, rerun: [execution](https://eu-west-3.console.aws.amazon.com/states/home?region=eu-west-3#/v2/executions/details/arn:aws:states:eu-west-3:529773242634:execution:CT-Dynatrace-Environment-ServiceLevelObjective--863979e868cb4005ae896d26713:Dynatrace-Environment-ServiceLevelObjective-eab6d5ce977542b48e3ca0687a7369f)

2022-12-06 16:10 UTC, merged